/** NorthwestMeds orders and reviews API. Bind to northwestmeds-data.xlsx. */
const ORDERS_SHEET='orders';
const REVIEWS_SHEET='reviews-ratings';
const ORDER_HEADERS=['orderId','timestamp','channel','status','itemsJson','itemCount','subtotal','postage','total','currency','pageUrl','userAgent','utmSource','utmMedium','utmCampaign'];
const REVIEW_HEADERS=['reviewId','timestamp','product','productName','rating','name','email','review','status'];
function output_(v){return ContentService.createTextOutput(JSON.stringify(v)).setMimeType(ContentService.MimeType.JSON)}
function sheet_(n,h){const ss=SpreadsheetApp.getActiveSpreadsheet();let s=ss.getSheetByName(n);if(!s)s=ss.insertSheet(n);if(s.getLastRow()===0){s.getRange(1,1,1,h.length).setValues([h]);s.setFrozenRows(1);s.getRange(1,1,1,h.length).setFontWeight('bold').setBackground('#edf8f3')}return s}
function setup(){sheet_(ORDERS_SHEET,ORDER_HEADERS);sheet_(REVIEWS_SHEET,REVIEW_HEADERS);return {ok:true,spreadsheetId:SpreadsheetApp.getActiveSpreadsheet().getId(),spreadsheetUrl:SpreadsheetApp.getActiveSpreadsheet().getUrl()}}
function doGet(e){try{const action=String(e.parameter&&e.parameter.action||'listReviews');if(action==='health')return output_({ok:true,service:'NorthwestMeds data API',spreadsheetId:SpreadsheetApp.getActiveSpreadsheet().getId()});if(action!=='listReviews')return output_({ok:false,error:'Unsupported action'});const product=String(e.parameter&&e.parameter.product||'').trim(),s=sheet_(REVIEWS_SHEET,REVIEW_HEADERS);if(s.getLastRow()<2)return output_({ok:true,reviews:[],spreadsheetId:SpreadsheetApp.getActiveSpreadsheet().getId()});const reviews=s.getRange(2,1,s.getLastRow()-1,REVIEW_HEADERS.length).getDisplayValues().map(r=>Object.fromEntries(REVIEW_HEADERS.map((h,i)=>[h,r[i]]))).filter(x=>x.status.toLowerCase()==='approved'&&(!product||x.product===product)).map(x=>({timestamp:x.timestamp,product:x.product,rating:Number(x.rating),name:x.name,review:x.review,status:x.status}));return output_({ok:true,reviews,spreadsheetId:SpreadsheetApp.getActiveSpreadsheet().getId()})}catch(error){return output_({ok:false,error:String(error.message||error)})}}
function createOrder_(v){const o=v.order||{},items=Array.isArray(o.items)?o.items:[];if(!o.orderId||!o.channel||!items.length)return {ok:false,error:'Missing order fields'};const s=sheet_(ORDERS_SHEET,ORDER_HEADERS),found=s.getLastRow()>1?s.getRange(2,1,s.getLastRow()-1,1).createTextFinder(String(o.orderId)).matchEntireCell(true).findNext():null;if(found)return {ok:true,orderId:o.orderId,duplicate:true,spreadsheetId:SpreadsheetApp.getActiveSpreadsheet().getId()};s.appendRow([String(o.orderId).slice(0,80),new Date(),String(o.channel).slice(0,20),'New',JSON.stringify(items).slice(0,45000),items.reduce((a,x)=>a+Number(x.quantity||1),0),Number(o.subtotal||0),Number(o.postage||0),Number(o.total||0),'GBP',String(o.pageUrl||'').slice(0,1000),String(v.userAgent||'').slice(0,500),String(o.utmSource||'').slice(0,200),String(o.utmMedium||'').slice(0,200),String(o.utmCampaign||'').slice(0,200)]);return {ok:true,orderId:o.orderId,spreadsheetId:SpreadsheetApp.getActiveSpreadsheet().getId()}}
function createReview_(v){if(v.website)return {ok:true};const rating=Number(v.rating);if(!v.product||!v.name||!v.email||!v.review||rating<1||rating>5)return {ok:false,error:'Missing or invalid review fields'};sheet_(REVIEWS_SHEET,REVIEW_HEADERS).appendRow([Utilities.getUuid(),new Date(),String(v.product).slice(0,100),String(v.productName||'').slice(0,150),rating,String(v.name).slice(0,60),String(v.email).slice(0,100),String(v.review).slice(0,1000),'Pending']);return {ok:true,status:'Pending',spreadsheetId:SpreadsheetApp.getActiveSpreadsheet().getId()}}
function doPost(e){const lock=LockService.getScriptLock();try{lock.waitLock(10000);const v=JSON.parse(e.postData&&e.postData.contents||'{}'),action=String(v.action||'createReview');return output_(action==='createOrder'?createOrder_(v):action==='createReview'?createReview_(v):{ok:false,error:'Unsupported action'})}catch(error){return output_({ok:false,error:String(error.message||error)})}finally{if(lock.hasLock())lock.releaseLock()}}
